language: php
php: 
  - '5.5'
  - '5.6'
  - '7.0'
#  - 'hhvm'
  - 'nightly'
env:
  global:
    - DBNAME='variation' 
    - DBUSER='deploy' 
    - DBPASS='variation'
services:
  - postgresql
addons:
  postgresql: "9.1"
install: 
  - composer install
  - ./scripts/install.sh
script: 
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml tests/
after_success:
  - travis_retry php vendor/bin/coveralls -v
